sdzblog_accueil:
    pattern:   /{page}
    defaults:  { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*
 
sdzblog_voir:
    pattern:   /article/{slug}
    defaults:  { _controller: SdzBlogBundle:Blog:voir }
 
sdzblog_ajouter:
    pattern:   /ajouter
    defaults:  { _controller: SdzBlogBundle:Blog:ajouter }
 
sdzblog_modifier:
    pattern:   /modifier/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        id:  \d+
 
sdzblog_supprimer:
    pattern:   /supprimer/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        id:  \d+
sdzblog_liste:
    pattern:   /{date}
    defaults:  { _controller: SdzBlogBundle:Blog:voirListe }
